### ISSUE TITLE
When using the URL resolver, the command will not be found if it has a trailing slash

### ISSUE THREAD

**Issue by JoeStead** [sequin/sequin#38] opened 2016-01-28 12:30 UTC
The URL resolver needs to strip and trailing slashes before trying to resolve the command.

![screen shot 2016-01-28 at 12 29 54](https://cloud.githubusercontent.com/assets/98282/12644456/e54437be-c5ba-11e5-9695-678b357793db.png)

**Comment by jasonmitchell** [comment] 2016-01-28 12:52
Debating whether this is a bug or not.

The URL resolver will capture everything after the base URL and pass that along (so in this case "RegisterUser/").  This specific issue is due to the fact that the ```ReflectionCommandRegistry``` is being used which identifies commands by type name.  Obviously "RegisterUser/" isn't a valid type name and it can't find it so this is caused by a combination of the user, url resolver and reflection registry.

I'm not convinced that I want to start tinkering with the resolved command name in anyway so as to not interfere with alternate ```ICommandRegistry``` implementations.

**Comment by JoeStead** [comment] 2016-01-28 13:44
Normally I'd agree, but I would expect "RegisterUser/" and "RegisterUser" to point to the same resource, the trailing slash is an irrelevant token.

**Comment by jasonmitchell** [comment] 2016-01-28 15:54
Commands != resources

**Comment by JoeStead** [comment] 2016-01-28 16:58
URL != Command

**Comment by jasonmitchell** [comment] 2016-01-29 09:59
I'm going to close this off as won't fix because it's impossible to say what people want to do with custom command registries.  It's much easier to say the default ```UrlCommandNameResolver``` has a catch-all behaviour rather than catch-all with exceptions.  Solutions to accommodate both behaviours are just adding unnecessary complexity.

The logic that trailing slash is the same as no slash is just plain incorrect.  However I do see your point since that is a convention provided by many web frameworks but at the most simple level it's just not how it works.  Consider a piece of OWIN middleware with the following code:

```csharp
if (context.Request.Path.Equals(new PathString("/someurl")))
{
    context.Response.Write("no trailing slash");
}
else if (context.Request.Path.Equals(new PathString("/someurl/")))
{
    context.Response.Write("trailing slash");
}
```

These URLs are handled differently.  

Sequin isn't trying to be a web framework which is as flexible as possible and catering for as many different use cases as possible out of the box; it's trying to provide a set of basic conventions (url command name resolution isn't even the default convention) which can be built upon and have swapped out in order to allow consumers to configure it in the manner that they want.

I don't consider this to be core library do to the fact that it's impossible to know all use-cases but if you really want/need this then I suggest a custom ```ICommandNameResolver``` which will handle this situation.

**Closed by jasonmitchell** 2016-01-29 09:59 UTC
Labels: question
